name: Release on npmjs.org
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      # pulls all tags (needed for lerna to correctly version)
      # - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308

      - uses: actions/setup-node@v3.4.0
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - run: git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
      - run: git config --global user.name ${{ secrets.GIT_USER_NAME }}

      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
      - run: npx lerna publish -y --no-verify-access
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
